package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"fmt"

	"github.com/vogtp/rag/pkg/usercfg/db/ent"
)

// Users is the resolver for the Users field.
func (r *queryResolver) Users(ctx context.Context, name *string) ([]*ent.Space, error) {
	panic(fmt.Errorf("not implemented: Users - Users"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
