package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"fmt"

	"github.com/vogtp/rag/pkg/usercfg/db/ent"
)

// Spaces is the resolver for the Spaces field.
func (r *confluenceResolver) Spaces(ctx context.Context, obj *ent.Confluence) ([]*ent.Space, error) {
	panic(fmt.Errorf("not implemented: Spaces - Spaces"))
}

// Confluence returns ConfluenceResolver implementation.
func (r *Resolver) Confluence() ConfluenceResolver { return &confluenceResolver{r} }

type confluenceResolver struct{ *Resolver }
