// Code generated by ent, DO NOT EDIT.

package space

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the space type in the database.
	Label = "space"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSpaceKey holds the string denoting the spacekey field in the database.
	FieldSpaceKey = "space_key"
	// Table holds the table name of the space in the database.
	Table = "spaces"
)

// Columns holds all SQL columns for space fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSpaceKey,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "spaces"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"collection_spaces",
	"confluence_spaces",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Space queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the Name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySpaceKey orders the results by the SpaceKey field.
func BySpaceKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpaceKey, opts...).ToFunc()
}
