// Code generated by ent, DO NOT EDIT.

package space

import (
	"entgo.io/ent/dialect/sql"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldName, v))
}

// SpaceKey applies equality check predicate on the "SpaceKey" field. It's identical to SpaceKeyEQ.
func SpaceKey(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldSpaceKey, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldName, v))
}

// SpaceKeyEQ applies the EQ predicate on the "SpaceKey" field.
func SpaceKeyEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldSpaceKey, v))
}

// SpaceKeyNEQ applies the NEQ predicate on the "SpaceKey" field.
func SpaceKeyNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldSpaceKey, v))
}

// SpaceKeyIn applies the In predicate on the "SpaceKey" field.
func SpaceKeyIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldSpaceKey, vs...))
}

// SpaceKeyNotIn applies the NotIn predicate on the "SpaceKey" field.
func SpaceKeyNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldSpaceKey, vs...))
}

// SpaceKeyGT applies the GT predicate on the "SpaceKey" field.
func SpaceKeyGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldSpaceKey, v))
}

// SpaceKeyGTE applies the GTE predicate on the "SpaceKey" field.
func SpaceKeyGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldSpaceKey, v))
}

// SpaceKeyLT applies the LT predicate on the "SpaceKey" field.
func SpaceKeyLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldSpaceKey, v))
}

// SpaceKeyLTE applies the LTE predicate on the "SpaceKey" field.
func SpaceKeyLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldSpaceKey, v))
}

// SpaceKeyContains applies the Contains predicate on the "SpaceKey" field.
func SpaceKeyContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldSpaceKey, v))
}

// SpaceKeyHasPrefix applies the HasPrefix predicate on the "SpaceKey" field.
func SpaceKeyHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldSpaceKey, v))
}

// SpaceKeyHasSuffix applies the HasSuffix predicate on the "SpaceKey" field.
func SpaceKeyHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldSpaceKey, v))
}

// SpaceKeyEqualFold applies the EqualFold predicate on the "SpaceKey" field.
func SpaceKeyEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldSpaceKey, v))
}

// SpaceKeyContainsFold applies the ContainsFold predicate on the "SpaceKey" field.
func SpaceKeyContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldSpaceKey, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Space) predicate.Space {
	return predicate.Space(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Space) predicate.Space {
	return predicate.Space(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Space) predicate.Space {
	return predicate.Space(sql.NotPredicates(p))
}
