// Code generated by ent, DO NOT EDIT.

package confluence

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Confluence {
	return predicate.Confluence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Confluence {
	return predicate.Confluence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Confluence {
	return predicate.Confluence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Confluence {
	return predicate.Confluence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Confluence {
	return predicate.Confluence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Confluence {
	return predicate.Confluence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Confluence {
	return predicate.Confluence(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldName, v))
}

// URL applies equality check predicate on the "URL" field. It's identical to URLEQ.
func URL(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldURL, v))
}

// ConfluenceAPIKey applies equality check predicate on the "ConfluenceAPIKey" field. It's identical to ConfluenceAPIKeyEQ.
func ConfluenceAPIKey(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldConfluenceAPIKey, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Confluence {
	return predicate.Confluence(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Confluence {
	return predicate.Confluence(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldContainsFold(FieldName, v))
}

// URLEQ applies the EQ predicate on the "URL" field.
func URLEQ(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "URL" field.
func URLNEQ(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "URL" field.
func URLIn(vs ...string) predicate.Confluence {
	return predicate.Confluence(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "URL" field.
func URLNotIn(vs ...string) predicate.Confluence {
	return predicate.Confluence(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "URL" field.
func URLGT(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "URL" field.
func URLGTE(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "URL" field.
func URLLT(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "URL" field.
func URLLTE(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "URL" field.
func URLContains(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "URL" field.
func URLHasPrefix(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "URL" field.
func URLHasSuffix(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "URL" field.
func URLEqualFold(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "URL" field.
func URLContainsFold(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldContainsFold(FieldURL, v))
}

// ConfluenceAPIKeyEQ applies the EQ predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyEQ(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEQ(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyNEQ applies the NEQ predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyNEQ(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldNEQ(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyIn applies the In predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyIn(vs ...string) predicate.Confluence {
	return predicate.Confluence(sql.FieldIn(FieldConfluenceAPIKey, vs...))
}

// ConfluenceAPIKeyNotIn applies the NotIn predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyNotIn(vs ...string) predicate.Confluence {
	return predicate.Confluence(sql.FieldNotIn(FieldConfluenceAPIKey, vs...))
}

// ConfluenceAPIKeyGT applies the GT predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyGT(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldGT(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyGTE applies the GTE predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyGTE(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldGTE(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyLT applies the LT predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyLT(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldLT(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyLTE applies the LTE predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyLTE(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldLTE(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyContains applies the Contains predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyContains(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldContains(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyHasPrefix applies the HasPrefix predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyHasPrefix(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldHasPrefix(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyHasSuffix applies the HasSuffix predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyHasSuffix(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldHasSuffix(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyEqualFold applies the EqualFold predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyEqualFold(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldEqualFold(FieldConfluenceAPIKey, v))
}

// ConfluenceAPIKeyContainsFold applies the ContainsFold predicate on the "ConfluenceAPIKey" field.
func ConfluenceAPIKeyContainsFold(v string) predicate.Confluence {
	return predicate.Confluence(sql.FieldContainsFold(FieldConfluenceAPIKey, v))
}

// HasSpaces applies the HasEdge predicate on the "Spaces" edge.
func HasSpaces() predicate.Confluence {
	return predicate.Confluence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SpacesTable, SpacesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSpacesWith applies the HasEdge predicate on the "Spaces" edge with a given conditions (other predicates).
func HasSpacesWith(preds ...predicate.Space) predicate.Confluence {
	return predicate.Confluence(func(s *sql.Selector) {
		step := newSpacesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Confluence) predicate.Confluence {
	return predicate.Confluence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Confluence) predicate.Confluence {
	return predicate.Confluence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Confluence) predicate.Confluence {
	return predicate.Confluence(sql.NotPredicates(p))
}
