// Code generated by ent, DO NOT EDIT.

package collection

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the collection type in the database.
	Label = "collection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAPIKey holds the string denoting the apikey field in the database.
	FieldAPIKey = "api_key"
	// FieldCollectionName holds the string denoting the collectionname field in the database.
	FieldCollectionName = "collection_name"
	// EdgeSources holds the string denoting the sources edge name in mutations.
	EdgeSources = "Sources"
	// Table holds the table name of the collection in the database.
	Table = "collections"
	// SourcesTable is the table that holds the Sources relation/edge.
	SourcesTable = "source_systems"
	// SourcesInverseTable is the table name for the SourceSystem entity.
	// It exists in this package in order to avoid circular dependency with the "sourcesystem" package.
	SourcesInverseTable = "source_systems"
	// SourcesColumn is the table column denoting the Sources relation/edge.
	SourcesColumn = "collection_sources"
)

// Columns holds all SQL columns for collection fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAPIKey,
	FieldCollectionName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "collections"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_collections",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Collection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the Name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAPIKey orders the results by the APIKey field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// ByCollectionName orders the results by the collectionName field.
func ByCollectionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionName, opts...).ToFunc()
}

// BySourcesCount orders the results by Sources count.
func BySourcesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSourcesStep(), opts...)
	}
}

// BySources orders the results by Sources terms.
func BySources(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourcesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSourcesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourcesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SourcesTable, SourcesColumn),
	)
}
