// Code generated by ent, DO NOT EDIT.

package collection

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Collection {
	return predicate.Collection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Collection {
	return predicate.Collection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Collection {
	return predicate.Collection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Collection {
	return predicate.Collection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Collection {
	return predicate.Collection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Collection {
	return predicate.Collection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Collection {
	return predicate.Collection(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldName, v))
}

// APIKey applies equality check predicate on the "APIKey" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldAPIKey, v))
}

// CollectionName applies equality check predicate on the "collectionName" field. It's identical to CollectionNameEQ.
func CollectionName(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldCollectionName, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Collection {
	return predicate.Collection(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Collection {
	return predicate.Collection(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Collection {
	return predicate.Collection(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Collection {
	return predicate.Collection(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Collection {
	return predicate.Collection(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Collection {
	return predicate.Collection(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Collection {
	return predicate.Collection(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Collection {
	return predicate.Collection(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Collection {
	return predicate.Collection(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Collection {
	return predicate.Collection(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Collection {
	return predicate.Collection(sql.FieldContainsFold(FieldName, v))
}

// APIKeyEQ applies the EQ predicate on the "APIKey" field.
func APIKeyEQ(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "APIKey" field.
func APIKeyNEQ(v string) predicate.Collection {
	return predicate.Collection(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "APIKey" field.
func APIKeyIn(vs ...string) predicate.Collection {
	return predicate.Collection(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "APIKey" field.
func APIKeyNotIn(vs ...string) predicate.Collection {
	return predicate.Collection(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "APIKey" field.
func APIKeyGT(v string) predicate.Collection {
	return predicate.Collection(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "APIKey" field.
func APIKeyGTE(v string) predicate.Collection {
	return predicate.Collection(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "APIKey" field.
func APIKeyLT(v string) predicate.Collection {
	return predicate.Collection(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "APIKey" field.
func APIKeyLTE(v string) predicate.Collection {
	return predicate.Collection(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "APIKey" field.
func APIKeyContains(v string) predicate.Collection {
	return predicate.Collection(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "APIKey" field.
func APIKeyHasPrefix(v string) predicate.Collection {
	return predicate.Collection(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "APIKey" field.
func APIKeyHasSuffix(v string) predicate.Collection {
	return predicate.Collection(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyIsNil applies the IsNil predicate on the "APIKey" field.
func APIKeyIsNil() predicate.Collection {
	return predicate.Collection(sql.FieldIsNull(FieldAPIKey))
}

// APIKeyNotNil applies the NotNil predicate on the "APIKey" field.
func APIKeyNotNil() predicate.Collection {
	return predicate.Collection(sql.FieldNotNull(FieldAPIKey))
}

// APIKeyEqualFold applies the EqualFold predicate on the "APIKey" field.
func APIKeyEqualFold(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "APIKey" field.
func APIKeyContainsFold(v string) predicate.Collection {
	return predicate.Collection(sql.FieldContainsFold(FieldAPIKey, v))
}

// CollectionNameEQ applies the EQ predicate on the "collectionName" field.
func CollectionNameEQ(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEQ(FieldCollectionName, v))
}

// CollectionNameNEQ applies the NEQ predicate on the "collectionName" field.
func CollectionNameNEQ(v string) predicate.Collection {
	return predicate.Collection(sql.FieldNEQ(FieldCollectionName, v))
}

// CollectionNameIn applies the In predicate on the "collectionName" field.
func CollectionNameIn(vs ...string) predicate.Collection {
	return predicate.Collection(sql.FieldIn(FieldCollectionName, vs...))
}

// CollectionNameNotIn applies the NotIn predicate on the "collectionName" field.
func CollectionNameNotIn(vs ...string) predicate.Collection {
	return predicate.Collection(sql.FieldNotIn(FieldCollectionName, vs...))
}

// CollectionNameGT applies the GT predicate on the "collectionName" field.
func CollectionNameGT(v string) predicate.Collection {
	return predicate.Collection(sql.FieldGT(FieldCollectionName, v))
}

// CollectionNameGTE applies the GTE predicate on the "collectionName" field.
func CollectionNameGTE(v string) predicate.Collection {
	return predicate.Collection(sql.FieldGTE(FieldCollectionName, v))
}

// CollectionNameLT applies the LT predicate on the "collectionName" field.
func CollectionNameLT(v string) predicate.Collection {
	return predicate.Collection(sql.FieldLT(FieldCollectionName, v))
}

// CollectionNameLTE applies the LTE predicate on the "collectionName" field.
func CollectionNameLTE(v string) predicate.Collection {
	return predicate.Collection(sql.FieldLTE(FieldCollectionName, v))
}

// CollectionNameContains applies the Contains predicate on the "collectionName" field.
func CollectionNameContains(v string) predicate.Collection {
	return predicate.Collection(sql.FieldContains(FieldCollectionName, v))
}

// CollectionNameHasPrefix applies the HasPrefix predicate on the "collectionName" field.
func CollectionNameHasPrefix(v string) predicate.Collection {
	return predicate.Collection(sql.FieldHasPrefix(FieldCollectionName, v))
}

// CollectionNameHasSuffix applies the HasSuffix predicate on the "collectionName" field.
func CollectionNameHasSuffix(v string) predicate.Collection {
	return predicate.Collection(sql.FieldHasSuffix(FieldCollectionName, v))
}

// CollectionNameIsNil applies the IsNil predicate on the "collectionName" field.
func CollectionNameIsNil() predicate.Collection {
	return predicate.Collection(sql.FieldIsNull(FieldCollectionName))
}

// CollectionNameNotNil applies the NotNil predicate on the "collectionName" field.
func CollectionNameNotNil() predicate.Collection {
	return predicate.Collection(sql.FieldNotNull(FieldCollectionName))
}

// CollectionNameEqualFold applies the EqualFold predicate on the "collectionName" field.
func CollectionNameEqualFold(v string) predicate.Collection {
	return predicate.Collection(sql.FieldEqualFold(FieldCollectionName, v))
}

// CollectionNameContainsFold applies the ContainsFold predicate on the "collectionName" field.
func CollectionNameContainsFold(v string) predicate.Collection {
	return predicate.Collection(sql.FieldContainsFold(FieldCollectionName, v))
}

// HasSources applies the HasEdge predicate on the "Sources" edge.
func HasSources() predicate.Collection {
	return predicate.Collection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SourcesTable, SourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourcesWith applies the HasEdge predicate on the "Sources" edge with a given conditions (other predicates).
func HasSourcesWith(preds ...predicate.SourceSystem) predicate.Collection {
	return predicate.Collection(func(s *sql.Selector) {
		step := newSourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Collection) predicate.Collection {
	return predicate.Collection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Collection) predicate.Collection {
	return predicate.Collection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Collection) predicate.Collection {
	return predicate.Collection(sql.NotPredicates(p))
}
