// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/collection"
)

// Collection is the model entity for the Collection schema.
type Collection struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// APIKey holds the value of the "APIKey" field.
	APIKey string `json:"APIKey,omitempty"`
	// CollectionName holds the value of the "collectionName" field.
	CollectionName string `json:"collectionName,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CollectionQuery when eager-loading is set.
	Edges            CollectionEdges `json:"edges"`
	user_collections *int
	selectValues     sql.SelectValues
}

// CollectionEdges holds the relations/edges for other nodes in the graph.
type CollectionEdges struct {
	// Sources holds the value of the Sources edge.
	Sources []*SourceSystem `json:"Sources,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedSources map[string][]*SourceSystem
}

// SourcesOrErr returns the Sources value or an error if the edge
// was not loaded in eager-loading.
func (e CollectionEdges) SourcesOrErr() ([]*SourceSystem, error) {
	if e.loadedTypes[0] {
		return e.Sources, nil
	}
	return nil, &NotLoadedError{edge: "Sources"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Collection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collection.FieldID:
			values[i] = new(sql.NullInt64)
		case collection.FieldName, collection.FieldAPIKey, collection.FieldCollectionName:
			values[i] = new(sql.NullString)
		case collection.ForeignKeys[0]: // user_collections
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Collection fields.
func (_m *Collection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case collection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case collection.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field APIKey", values[i])
			} else if value.Valid {
				_m.APIKey = value.String
			}
		case collection.FieldCollectionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collectionName", values[i])
			} else if value.Valid {
				_m.CollectionName = value.String
			}
		case collection.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_collections", value)
			} else if value.Valid {
				_m.user_collections = new(int)
				*_m.user_collections = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Collection.
// This includes values selected through modifiers, order, etc.
func (_m *Collection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySources queries the "Sources" edge of the Collection entity.
func (_m *Collection) QuerySources() *SourceSystemQuery {
	return NewCollectionClient(_m.config).QuerySources(_m)
}

// Update returns a builder for updating this Collection.
// Note that you need to call Collection.Unwrap() before calling this method if this Collection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Collection) Update() *CollectionUpdateOne {
	return NewCollectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Collection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Collection) Unwrap() *Collection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Collection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Collection) String() string {
	var builder strings.Builder
	builder.WriteString("Collection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("Name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("APIKey=")
	builder.WriteString(_m.APIKey)
	builder.WriteString(", ")
	builder.WriteString("collectionName=")
	builder.WriteString(_m.CollectionName)
	builder.WriteByte(')')
	return builder.String()
}

// NamedSources returns the Sources named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Collection) NamedSources(name string) ([]*SourceSystem, error) {
	if _m.Edges.namedSources == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedSources[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Collection) appendNamedSources(name string, edges ...*SourceSystem) {
	if _m.Edges.namedSources == nil {
		_m.Edges.namedSources = make(map[string][]*SourceSystem)
	}
	if len(edges) == 0 {
		_m.Edges.namedSources[name] = []*SourceSystem{}
	} else {
		_m.Edges.namedSources[name] = append(_m.Edges.namedSources[name], edges...)
	}
}

// Collections is a parsable slice of Collection.
type Collections []*Collection
