// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/collection"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/sourcesystem"
)

// CollectionUpdate is the builder for updating Collection entities.
type CollectionUpdate struct {
	config
	hooks    []Hook
	mutation *CollectionMutation
}

// Where appends a list predicates to the CollectionUpdate builder.
func (_u *CollectionUpdate) Where(ps ...predicate.Collection) *CollectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "Name" field.
func (_u *CollectionUpdate) SetName(v string) *CollectionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableName(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIKey sets the "APIKey" field.
func (_u *CollectionUpdate) SetAPIKey(v string) *CollectionUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "APIKey" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableAPIKey(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "APIKey" field.
func (_u *CollectionUpdate) ClearAPIKey() *CollectionUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetCollectionName sets the "collectionName" field.
func (_u *CollectionUpdate) SetCollectionName(v string) *CollectionUpdate {
	_u.mutation.SetCollectionName(v)
	return _u
}

// SetNillableCollectionName sets the "collectionName" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableCollectionName(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetCollectionName(*v)
	}
	return _u
}

// ClearCollectionName clears the value of the "collectionName" field.
func (_u *CollectionUpdate) ClearCollectionName() *CollectionUpdate {
	_u.mutation.ClearCollectionName()
	return _u
}

// AddSourceIDs adds the "Sources" edge to the SourceSystem entity by IDs.
func (_u *CollectionUpdate) AddSourceIDs(ids ...int) *CollectionUpdate {
	_u.mutation.AddSourceIDs(ids...)
	return _u
}

// AddSources adds the "Sources" edges to the SourceSystem entity.
func (_u *CollectionUpdate) AddSources(v ...*SourceSystem) *CollectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceIDs(ids...)
}

// Mutation returns the CollectionMutation object of the builder.
func (_u *CollectionUpdate) Mutation() *CollectionMutation {
	return _u.mutation
}

// ClearSources clears all "Sources" edges to the SourceSystem entity.
func (_u *CollectionUpdate) ClearSources() *CollectionUpdate {
	_u.mutation.ClearSources()
	return _u
}

// RemoveSourceIDs removes the "Sources" edge to SourceSystem entities by IDs.
func (_u *CollectionUpdate) RemoveSourceIDs(ids ...int) *CollectionUpdate {
	_u.mutation.RemoveSourceIDs(ids...)
	return _u
}

// RemoveSources removes "Sources" edges to SourceSystem entities.
func (_u *CollectionUpdate) RemoveSources(v ...*SourceSystem) *CollectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollectionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CollectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(collection.Table, collection.Columns, sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(collection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(collection.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(collection.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.CollectionName(); ok {
		_spec.SetField(collection.FieldCollectionName, field.TypeString, value)
	}
	if _u.mutation.CollectionNameCleared() {
		_spec.ClearField(collection.FieldCollectionName, field.TypeString)
	}
	if _u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.SourcesTable,
			Columns: []string{collection.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourcesIDs(); len(nodes) > 0 && !_u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.SourcesTable,
			Columns: []string{collection.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.SourcesTable,
			Columns: []string{collection.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollectionUpdateOne is the builder for updating a single Collection entity.
type CollectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollectionMutation
}

// SetName sets the "Name" field.
func (_u *CollectionUpdateOne) SetName(v string) *CollectionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableName(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIKey sets the "APIKey" field.
func (_u *CollectionUpdateOne) SetAPIKey(v string) *CollectionUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "APIKey" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableAPIKey(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "APIKey" field.
func (_u *CollectionUpdateOne) ClearAPIKey() *CollectionUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetCollectionName sets the "collectionName" field.
func (_u *CollectionUpdateOne) SetCollectionName(v string) *CollectionUpdateOne {
	_u.mutation.SetCollectionName(v)
	return _u
}

// SetNillableCollectionName sets the "collectionName" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableCollectionName(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetCollectionName(*v)
	}
	return _u
}

// ClearCollectionName clears the value of the "collectionName" field.
func (_u *CollectionUpdateOne) ClearCollectionName() *CollectionUpdateOne {
	_u.mutation.ClearCollectionName()
	return _u
}

// AddSourceIDs adds the "Sources" edge to the SourceSystem entity by IDs.
func (_u *CollectionUpdateOne) AddSourceIDs(ids ...int) *CollectionUpdateOne {
	_u.mutation.AddSourceIDs(ids...)
	return _u
}

// AddSources adds the "Sources" edges to the SourceSystem entity.
func (_u *CollectionUpdateOne) AddSources(v ...*SourceSystem) *CollectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceIDs(ids...)
}

// Mutation returns the CollectionMutation object of the builder.
func (_u *CollectionUpdateOne) Mutation() *CollectionMutation {
	return _u.mutation
}

// ClearSources clears all "Sources" edges to the SourceSystem entity.
func (_u *CollectionUpdateOne) ClearSources() *CollectionUpdateOne {
	_u.mutation.ClearSources()
	return _u
}

// RemoveSourceIDs removes the "Sources" edge to SourceSystem entities by IDs.
func (_u *CollectionUpdateOne) RemoveSourceIDs(ids ...int) *CollectionUpdateOne {
	_u.mutation.RemoveSourceIDs(ids...)
	return _u
}

// RemoveSources removes "Sources" edges to SourceSystem entities.
func (_u *CollectionUpdateOne) RemoveSources(v ...*SourceSystem) *CollectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceIDs(ids...)
}

// Where appends a list predicates to the CollectionUpdate builder.
func (_u *CollectionUpdateOne) Where(ps ...predicate.Collection) *CollectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollectionUpdateOne) Select(field string, fields ...string) *CollectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Collection entity.
func (_u *CollectionUpdateOne) Save(ctx context.Context) (*Collection, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionUpdateOne) SaveX(ctx context.Context) *Collection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CollectionUpdateOne) sqlSave(ctx context.Context) (_node *Collection, err error) {
	_spec := sqlgraph.NewUpdateSpec(collection.Table, collection.Columns, sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Collection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collection.FieldID)
		for _, f := range fields {
			if !collection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(collection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(collection.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(collection.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.CollectionName(); ok {
		_spec.SetField(collection.FieldCollectionName, field.TypeString, value)
	}
	if _u.mutation.CollectionNameCleared() {
		_spec.ClearField(collection.FieldCollectionName, field.TypeString)
	}
	if _u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.SourcesTable,
			Columns: []string{collection.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourcesIDs(); len(nodes) > 0 && !_u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.SourcesTable,
			Columns: []string{collection.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.SourcesTable,
			Columns: []string{collection.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Collection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
