// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/confluence"
)

// Confluence is the model entity for the Confluence schema.
type Confluence struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// URL holds the value of the "URL" field.
	URL string `json:"URL,omitempty"`
	// ConfluenceAPIKey holds the value of the "ConfluenceAPIKey" field.
	ConfluenceAPIKey string `json:"ConfluenceAPIKey,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConfluenceQuery when eager-loading is set.
	Edges           ConfluenceEdges `json:"edges"`
	user_confluence *int
	selectValues    sql.SelectValues
}

// ConfluenceEdges holds the relations/edges for other nodes in the graph.
type ConfluenceEdges struct {
	// Spaces holds the value of the Spaces edge.
	Spaces []*Space `json:"Spaces,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedSpaces map[string][]*Space
}

// SpacesOrErr returns the Spaces value or an error if the edge
// was not loaded in eager-loading.
func (e ConfluenceEdges) SpacesOrErr() ([]*Space, error) {
	if e.loadedTypes[0] {
		return e.Spaces, nil
	}
	return nil, &NotLoadedError{edge: "Spaces"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Confluence) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case confluence.FieldID:
			values[i] = new(sql.NullInt64)
		case confluence.FieldName, confluence.FieldURL, confluence.FieldConfluenceAPIKey:
			values[i] = new(sql.NullString)
		case confluence.ForeignKeys[0]: // user_confluence
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Confluence fields.
func (c *Confluence) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case confluence.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case confluence.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case confluence.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field URL", values[i])
			} else if value.Valid {
				c.URL = value.String
			}
		case confluence.FieldConfluenceAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ConfluenceAPIKey", values[i])
			} else if value.Valid {
				c.ConfluenceAPIKey = value.String
			}
		case confluence.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_confluence", value)
			} else if value.Valid {
				c.user_confluence = new(int)
				*c.user_confluence = int(value.Int64)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Confluence.
// This includes values selected through modifiers, order, etc.
func (c *Confluence) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QuerySpaces queries the "Spaces" edge of the Confluence entity.
func (c *Confluence) QuerySpaces() *SpaceQuery {
	return NewConfluenceClient(c.config).QuerySpaces(c)
}

// Update returns a builder for updating this Confluence.
// Note that you need to call Confluence.Unwrap() before calling this method if this Confluence
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Confluence) Update() *ConfluenceUpdateOne {
	return NewConfluenceClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Confluence entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Confluence) Unwrap() *Confluence {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Confluence is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Confluence) String() string {
	var builder strings.Builder
	builder.WriteString("Confluence(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("Name=")
	builder.WriteString(c.Name)
	builder.WriteString(", ")
	builder.WriteString("URL=")
	builder.WriteString(c.URL)
	builder.WriteString(", ")
	builder.WriteString("ConfluenceAPIKey=")
	builder.WriteString(c.ConfluenceAPIKey)
	builder.WriteByte(')')
	return builder.String()
}

// NamedSpaces returns the Spaces named value or an error if the edge was not
// loaded in eager-loading with this name.
func (c *Confluence) NamedSpaces(name string) ([]*Space, error) {
	if c.Edges.namedSpaces == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := c.Edges.namedSpaces[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (c *Confluence) appendNamedSpaces(name string, edges ...*Space) {
	if c.Edges.namedSpaces == nil {
		c.Edges.namedSpaces = make(map[string][]*Space)
	}
	if len(edges) == 0 {
		c.Edges.namedSpaces[name] = []*Space{}
	} else {
		c.Edges.namedSpaces[name] = append(c.Edges.namedSpaces[name], edges...)
	}
}

// Confluences is a parsable slice of Confluence.
type Confluences []*Confluence
