// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/confluence"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
)

// ConfluenceDelete is the builder for deleting a Confluence entity.
type ConfluenceDelete struct {
	config
	hooks    []Hook
	mutation *ConfluenceMutation
}

// Where appends a list predicates to the ConfluenceDelete builder.
func (cd *ConfluenceDelete) Where(ps ...predicate.Confluence) *ConfluenceDelete {
	cd.mutation.Where(ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *ConfluenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cd.sqlExec, cd.mutation, cd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *ConfluenceDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *ConfluenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(confluence.Table, sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt))
	if ps := cd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cd.mutation.done = true
	return affected, err
}

// ConfluenceDeleteOne is the builder for deleting a single Confluence entity.
type ConfluenceDeleteOne struct {
	cd *ConfluenceDelete
}

// Where appends a list predicates to the ConfluenceDelete builder.
func (cdo *ConfluenceDeleteOne) Where(ps ...predicate.Confluence) *ConfluenceDeleteOne {
	cdo.cd.mutation.Where(ps...)
	return cdo
}

// Exec executes the deletion query.
func (cdo *ConfluenceDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{confluence.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *ConfluenceDeleteOne) ExecX(ctx context.Context) {
	if err := cdo.Exec(ctx); err != nil {
		panic(err)
	}
}
