// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/confluence"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/space"
)

// ConfluenceQuery is the builder for querying Confluence entities.
type ConfluenceQuery struct {
	config
	ctx             *QueryContext
	order           []confluence.OrderOption
	inters          []Interceptor
	predicates      []predicate.Confluence
	withSpaces      *SpaceQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	loadTotal       []func(context.Context, []*Confluence) error
	withNamedSpaces map[string]*SpaceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ConfluenceQuery builder.
func (cq *ConfluenceQuery) Where(ps ...predicate.Confluence) *ConfluenceQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ConfluenceQuery) Limit(limit int) *ConfluenceQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ConfluenceQuery) Offset(offset int) *ConfluenceQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ConfluenceQuery) Unique(unique bool) *ConfluenceQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ConfluenceQuery) Order(o ...confluence.OrderOption) *ConfluenceQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QuerySpaces chains the current query on the "Spaces" edge.
func (cq *ConfluenceQuery) QuerySpaces() *SpaceQuery {
	query := (&SpaceClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(confluence.Table, confluence.FieldID, selector),
			sqlgraph.To(space.Table, space.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, confluence.SpacesTable, confluence.SpacesColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Confluence entity from the query.
// Returns a *NotFoundError when no Confluence was found.
func (cq *ConfluenceQuery) First(ctx context.Context) (*Confluence, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{confluence.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ConfluenceQuery) FirstX(ctx context.Context) *Confluence {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Confluence ID from the query.
// Returns a *NotFoundError when no Confluence ID was found.
func (cq *ConfluenceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{confluence.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ConfluenceQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Confluence entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Confluence entity is found.
// Returns a *NotFoundError when no Confluence entities are found.
func (cq *ConfluenceQuery) Only(ctx context.Context) (*Confluence, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{confluence.Label}
	default:
		return nil, &NotSingularError{confluence.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ConfluenceQuery) OnlyX(ctx context.Context) *Confluence {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Confluence ID in the query.
// Returns a *NotSingularError when more than one Confluence ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ConfluenceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{confluence.Label}
	default:
		err = &NotSingularError{confluence.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ConfluenceQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Confluences.
func (cq *ConfluenceQuery) All(ctx context.Context) ([]*Confluence, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Confluence, *ConfluenceQuery]()
	return withInterceptors[[]*Confluence](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ConfluenceQuery) AllX(ctx context.Context) []*Confluence {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Confluence IDs.
func (cq *ConfluenceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(confluence.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ConfluenceQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ConfluenceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ConfluenceQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ConfluenceQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ConfluenceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ConfluenceQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ConfluenceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ConfluenceQuery) Clone() *ConfluenceQuery {
	if cq == nil {
		return nil
	}
	return &ConfluenceQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]confluence.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.Confluence{}, cq.predicates...),
		withSpaces: cq.withSpaces.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithSpaces tells the query-builder to eager-load the nodes that are connected to
// the "Spaces" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ConfluenceQuery) WithSpaces(opts ...func(*SpaceQuery)) *ConfluenceQuery {
	query := (&SpaceClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withSpaces = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Confluence.Query().
//		GroupBy(confluence.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ConfluenceQuery) GroupBy(field string, fields ...string) *ConfluenceGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ConfluenceGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = confluence.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.Confluence.Query().
//		Select(confluence.FieldName).
//		Scan(ctx, &v)
func (cq *ConfluenceQuery) Select(fields ...string) *ConfluenceSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ConfluenceSelect{ConfluenceQuery: cq}
	sbuild.label = confluence.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ConfluenceSelect configured with the given aggregations.
func (cq *ConfluenceQuery) Aggregate(fns ...AggregateFunc) *ConfluenceSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ConfluenceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !confluence.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ConfluenceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Confluence, error) {
	var (
		nodes       = []*Confluence{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withSpaces != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, confluence.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Confluence).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Confluence{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withSpaces; query != nil {
		if err := cq.loadSpaces(ctx, query, nodes,
			func(n *Confluence) { n.Edges.Spaces = []*Space{} },
			func(n *Confluence, e *Space) { n.Edges.Spaces = append(n.Edges.Spaces, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range cq.withNamedSpaces {
		if err := cq.loadSpaces(ctx, query, nodes,
			func(n *Confluence) { n.appendNamedSpaces(name) },
			func(n *Confluence, e *Space) { n.appendNamedSpaces(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range cq.loadTotal {
		if err := cq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ConfluenceQuery) loadSpaces(ctx context.Context, query *SpaceQuery, nodes []*Confluence, init func(*Confluence), assign func(*Confluence, *Space)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Confluence)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Space(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(confluence.SpacesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.confluence_spaces
		if fk == nil {
			return fmt.Errorf(`foreign-key "confluence_spaces" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "confluence_spaces" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *ConfluenceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ConfluenceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(confluence.Table, confluence.Columns, sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, confluence.FieldID)
		for i := range fields {
			if fields[i] != confluence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ConfluenceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(confluence.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = confluence.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedSpaces tells the query-builder to eager-load the nodes that are connected to the "Spaces"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (cq *ConfluenceQuery) WithNamedSpaces(name string, opts ...func(*SpaceQuery)) *ConfluenceQuery {
	query := (&SpaceClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if cq.withNamedSpaces == nil {
		cq.withNamedSpaces = make(map[string]*SpaceQuery)
	}
	cq.withNamedSpaces[name] = query
	return cq
}

// ConfluenceGroupBy is the group-by builder for Confluence entities.
type ConfluenceGroupBy struct {
	selector
	build *ConfluenceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ConfluenceGroupBy) Aggregate(fns ...AggregateFunc) *ConfluenceGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ConfluenceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConfluenceQuery, *ConfluenceGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ConfluenceGroupBy) sqlScan(ctx context.Context, root *ConfluenceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ConfluenceSelect is the builder for selecting fields of Confluence entities.
type ConfluenceSelect struct {
	*ConfluenceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ConfluenceSelect) Aggregate(fns ...AggregateFunc) *ConfluenceSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ConfluenceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConfluenceQuery, *ConfluenceSelect](ctx, cs.ConfluenceQuery, cs, cs.inters, v)
}

func (cs *ConfluenceSelect) sqlScan(ctx context.Context, root *ConfluenceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
