// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Collection) Sources(ctx context.Context) (result []*SourceSystem, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSources(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SourcesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySources().All(ctx)
	}
	return result, err
}

func (_m *User) Collections(ctx context.Context) (result []*Collection, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCollections(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CollectionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCollections().All(ctx)
	}
	return result, err
}
