// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/sourcesystem"
)

// SourceSystemCreate is the builder for creating a SourceSystem entity.
type SourceSystemCreate struct {
	config
	mutation *SourceSystemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "Name" field.
func (ssc *SourceSystemCreate) SetName(s string) *SourceSystemCreate {
	ssc.mutation.SetName(s)
	return ssc
}

// SetType sets the "Type" field.
func (ssc *SourceSystemCreate) SetType(s sourcesystem.Type) *SourceSystemCreate {
	ssc.mutation.SetType(s)
	return ssc
}

// SetURL sets the "URL" field.
func (ssc *SourceSystemCreate) SetURL(s string) *SourceSystemCreate {
	ssc.mutation.SetURL(s)
	return ssc
}

// SetKey sets the "key" field.
func (ssc *SourceSystemCreate) SetKey(s string) *SourceSystemCreate {
	ssc.mutation.SetKey(s)
	return ssc
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (ssc *SourceSystemCreate) SetNillableKey(s *string) *SourceSystemCreate {
	if s != nil {
		ssc.SetKey(*s)
	}
	return ssc
}

// SetParts sets the "parts" field.
func (ssc *SourceSystemCreate) SetParts(s string) *SourceSystemCreate {
	ssc.mutation.SetParts(s)
	return ssc
}

// SetNillableParts sets the "parts" field if the given value is not nil.
func (ssc *SourceSystemCreate) SetNillableParts(s *string) *SourceSystemCreate {
	if s != nil {
		ssc.SetParts(*s)
	}
	return ssc
}

// Mutation returns the SourceSystemMutation object of the builder.
func (ssc *SourceSystemCreate) Mutation() *SourceSystemMutation {
	return ssc.mutation
}

// Save creates the SourceSystem in the database.
func (ssc *SourceSystemCreate) Save(ctx context.Context) (*SourceSystem, error) {
	return withHooks(ctx, ssc.sqlSave, ssc.mutation, ssc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ssc *SourceSystemCreate) SaveX(ctx context.Context) *SourceSystem {
	v, err := ssc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssc *SourceSystemCreate) Exec(ctx context.Context) error {
	_, err := ssc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssc *SourceSystemCreate) ExecX(ctx context.Context) {
	if err := ssc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssc *SourceSystemCreate) check() error {
	if _, ok := ssc.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "SourceSystem.Name"`)}
	}
	if _, ok := ssc.mutation.GetType(); !ok {
		return &ValidationError{Name: "Type", err: errors.New(`ent: missing required field "SourceSystem.Type"`)}
	}
	if v, ok := ssc.mutation.GetType(); ok {
		if err := sourcesystem.TypeValidator(v); err != nil {
			return &ValidationError{Name: "Type", err: fmt.Errorf(`ent: validator failed for field "SourceSystem.Type": %w`, err)}
		}
	}
	if _, ok := ssc.mutation.URL(); !ok {
		return &ValidationError{Name: "URL", err: errors.New(`ent: missing required field "SourceSystem.URL"`)}
	}
	return nil
}

func (ssc *SourceSystemCreate) sqlSave(ctx context.Context) (*SourceSystem, error) {
	if err := ssc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ssc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ssc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ssc.mutation.id = &_node.ID
	ssc.mutation.done = true
	return _node, nil
}

func (ssc *SourceSystemCreate) createSpec() (*SourceSystem, *sqlgraph.CreateSpec) {
	var (
		_node = &SourceSystem{config: ssc.config}
		_spec = sqlgraph.NewCreateSpec(sourcesystem.Table, sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ssc.conflict
	if value, ok := ssc.mutation.Name(); ok {
		_spec.SetField(sourcesystem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ssc.mutation.GetType(); ok {
		_spec.SetField(sourcesystem.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := ssc.mutation.URL(); ok {
		_spec.SetField(sourcesystem.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := ssc.mutation.Key(); ok {
		_spec.SetField(sourcesystem.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := ssc.mutation.Parts(); ok {
		_spec.SetField(sourcesystem.FieldParts, field.TypeString, value)
		_node.Parts = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SourceSystem.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceSystemUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (ssc *SourceSystemCreate) OnConflict(opts ...sql.ConflictOption) *SourceSystemUpsertOne {
	ssc.conflict = opts
	return &SourceSystemUpsertOne{
		create: ssc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ssc *SourceSystemCreate) OnConflictColumns(columns ...string) *SourceSystemUpsertOne {
	ssc.conflict = append(ssc.conflict, sql.ConflictColumns(columns...))
	return &SourceSystemUpsertOne{
		create: ssc,
	}
}

type (
	// SourceSystemUpsertOne is the builder for "upsert"-ing
	//  one SourceSystem node.
	SourceSystemUpsertOne struct {
		create *SourceSystemCreate
	}

	// SourceSystemUpsert is the "OnConflict" setter.
	SourceSystemUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "Name" field.
func (u *SourceSystemUpsert) SetName(v string) *SourceSystemUpsert {
	u.Set(sourcesystem.FieldName, v)
	return u
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *SourceSystemUpsert) UpdateName() *SourceSystemUpsert {
	u.SetExcluded(sourcesystem.FieldName)
	return u
}

// SetType sets the "Type" field.
func (u *SourceSystemUpsert) SetType(v sourcesystem.Type) *SourceSystemUpsert {
	u.Set(sourcesystem.FieldType, v)
	return u
}

// UpdateType sets the "Type" field to the value that was provided on create.
func (u *SourceSystemUpsert) UpdateType() *SourceSystemUpsert {
	u.SetExcluded(sourcesystem.FieldType)
	return u
}

// SetURL sets the "URL" field.
func (u *SourceSystemUpsert) SetURL(v string) *SourceSystemUpsert {
	u.Set(sourcesystem.FieldURL, v)
	return u
}

// UpdateURL sets the "URL" field to the value that was provided on create.
func (u *SourceSystemUpsert) UpdateURL() *SourceSystemUpsert {
	u.SetExcluded(sourcesystem.FieldURL)
	return u
}

// SetKey sets the "key" field.
func (u *SourceSystemUpsert) SetKey(v string) *SourceSystemUpsert {
	u.Set(sourcesystem.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SourceSystemUpsert) UpdateKey() *SourceSystemUpsert {
	u.SetExcluded(sourcesystem.FieldKey)
	return u
}

// ClearKey clears the value of the "key" field.
func (u *SourceSystemUpsert) ClearKey() *SourceSystemUpsert {
	u.SetNull(sourcesystem.FieldKey)
	return u
}

// SetParts sets the "parts" field.
func (u *SourceSystemUpsert) SetParts(v string) *SourceSystemUpsert {
	u.Set(sourcesystem.FieldParts, v)
	return u
}

// UpdateParts sets the "parts" field to the value that was provided on create.
func (u *SourceSystemUpsert) UpdateParts() *SourceSystemUpsert {
	u.SetExcluded(sourcesystem.FieldParts)
	return u
}

// ClearParts clears the value of the "parts" field.
func (u *SourceSystemUpsert) ClearParts() *SourceSystemUpsert {
	u.SetNull(sourcesystem.FieldParts)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SourceSystemUpsertOne) UpdateNewValues() *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SourceSystemUpsertOne) Ignore() *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceSystemUpsertOne) DoNothing() *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceSystemCreate.OnConflict
// documentation for more info.
func (u *SourceSystemUpsertOne) Update(set func(*SourceSystemUpsert)) *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceSystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "Name" field.
func (u *SourceSystemUpsertOne) SetName(v string) *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *SourceSystemUpsertOne) UpdateName() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "Type" field.
func (u *SourceSystemUpsertOne) SetType(v sourcesystem.Type) *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "Type" field to the value that was provided on create.
func (u *SourceSystemUpsertOne) UpdateType() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateType()
	})
}

// SetURL sets the "URL" field.
func (u *SourceSystemUpsertOne) SetURL(v string) *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "URL" field to the value that was provided on create.
func (u *SourceSystemUpsertOne) UpdateURL() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateURL()
	})
}

// SetKey sets the "key" field.
func (u *SourceSystemUpsertOne) SetKey(v string) *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SourceSystemUpsertOne) UpdateKey() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateKey()
	})
}

// ClearKey clears the value of the "key" field.
func (u *SourceSystemUpsertOne) ClearKey() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.ClearKey()
	})
}

// SetParts sets the "parts" field.
func (u *SourceSystemUpsertOne) SetParts(v string) *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetParts(v)
	})
}

// UpdateParts sets the "parts" field to the value that was provided on create.
func (u *SourceSystemUpsertOne) UpdateParts() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateParts()
	})
}

// ClearParts clears the value of the "parts" field.
func (u *SourceSystemUpsertOne) ClearParts() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.ClearParts()
	})
}

// Exec executes the query.
func (u *SourceSystemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SourceSystemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceSystemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SourceSystemUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SourceSystemUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SourceSystemCreateBulk is the builder for creating many SourceSystem entities in bulk.
type SourceSystemCreateBulk struct {
	config
	err      error
	builders []*SourceSystemCreate
	conflict []sql.ConflictOption
}

// Save creates the SourceSystem entities in the database.
func (sscb *SourceSystemCreateBulk) Save(ctx context.Context) ([]*SourceSystem, error) {
	if sscb.err != nil {
		return nil, sscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sscb.builders))
	nodes := make([]*SourceSystem, len(sscb.builders))
	mutators := make([]Mutator, len(sscb.builders))
	for i := range sscb.builders {
		func(i int, root context.Context) {
			builder := sscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceSystemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = sscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sscb *SourceSystemCreateBulk) SaveX(ctx context.Context) []*SourceSystem {
	v, err := sscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sscb *SourceSystemCreateBulk) Exec(ctx context.Context) error {
	_, err := sscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sscb *SourceSystemCreateBulk) ExecX(ctx context.Context) {
	if err := sscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SourceSystem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceSystemUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (sscb *SourceSystemCreateBulk) OnConflict(opts ...sql.ConflictOption) *SourceSystemUpsertBulk {
	sscb.conflict = opts
	return &SourceSystemUpsertBulk{
		create: sscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sscb *SourceSystemCreateBulk) OnConflictColumns(columns ...string) *SourceSystemUpsertBulk {
	sscb.conflict = append(sscb.conflict, sql.ConflictColumns(columns...))
	return &SourceSystemUpsertBulk{
		create: sscb,
	}
}

// SourceSystemUpsertBulk is the builder for "upsert"-ing
// a bulk of SourceSystem nodes.
type SourceSystemUpsertBulk struct {
	create *SourceSystemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SourceSystemUpsertBulk) UpdateNewValues() *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SourceSystemUpsertBulk) Ignore() *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceSystemUpsertBulk) DoNothing() *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceSystemCreateBulk.OnConflict
// documentation for more info.
func (u *SourceSystemUpsertBulk) Update(set func(*SourceSystemUpsert)) *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceSystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "Name" field.
func (u *SourceSystemUpsertBulk) SetName(v string) *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *SourceSystemUpsertBulk) UpdateName() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "Type" field.
func (u *SourceSystemUpsertBulk) SetType(v sourcesystem.Type) *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "Type" field to the value that was provided on create.
func (u *SourceSystemUpsertBulk) UpdateType() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateType()
	})
}

// SetURL sets the "URL" field.
func (u *SourceSystemUpsertBulk) SetURL(v string) *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "URL" field to the value that was provided on create.
func (u *SourceSystemUpsertBulk) UpdateURL() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateURL()
	})
}

// SetKey sets the "key" field.
func (u *SourceSystemUpsertBulk) SetKey(v string) *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SourceSystemUpsertBulk) UpdateKey() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateKey()
	})
}

// ClearKey clears the value of the "key" field.
func (u *SourceSystemUpsertBulk) ClearKey() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.ClearKey()
	})
}

// SetParts sets the "parts" field.
func (u *SourceSystemUpsertBulk) SetParts(v string) *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetParts(v)
	})
}

// UpdateParts sets the "parts" field to the value that was provided on create.
func (u *SourceSystemUpsertBulk) UpdateParts() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateParts()
	})
}

// ClearParts clears the value of the "parts" field.
func (u *SourceSystemUpsertBulk) ClearParts() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.ClearParts()
	})
}

// Exec executes the query.
func (u *SourceSystemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SourceSystemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SourceSystemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceSystemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
