// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/sourcesystem"
)

// SourceSystem is the model entity for the SourceSystem schema.
type SourceSystem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Type holds the value of the "Type" field.
	Type sourcesystem.Type `json:"Type,omitempty"`
	// URL holds the value of the "URL" field.
	URL string `json:"URL,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Parts holds the value of the "parts" field.
	Parts              string `json:"parts,omitempty"`
	collection_sources *int
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SourceSystem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sourcesystem.FieldID:
			values[i] = new(sql.NullInt64)
		case sourcesystem.FieldName, sourcesystem.FieldType, sourcesystem.FieldURL, sourcesystem.FieldKey, sourcesystem.FieldParts:
			values[i] = new(sql.NullString)
		case sourcesystem.ForeignKeys[0]: // collection_sources
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SourceSystem fields.
func (_m *SourceSystem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sourcesystem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sourcesystem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sourcesystem.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Type", values[i])
			} else if value.Valid {
				_m.Type = sourcesystem.Type(value.String)
			}
		case sourcesystem.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field URL", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case sourcesystem.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case sourcesystem.FieldParts:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parts", values[i])
			} else if value.Valid {
				_m.Parts = value.String
			}
		case sourcesystem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field collection_sources", value)
			} else if value.Valid {
				_m.collection_sources = new(int)
				*_m.collection_sources = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SourceSystem.
// This includes values selected through modifiers, order, etc.
func (_m *SourceSystem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SourceSystem.
// Note that you need to call SourceSystem.Unwrap() before calling this method if this SourceSystem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SourceSystem) Update() *SourceSystemUpdateOne {
	return NewSourceSystemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SourceSystem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SourceSystem) Unwrap() *SourceSystem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SourceSystem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SourceSystem) String() string {
	var builder strings.Builder
	builder.WriteString("SourceSystem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("Name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("Type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("URL=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("parts=")
	builder.WriteString(_m.Parts)
	builder.WriteByte(')')
	return builder.String()
}

// SourceSystems is a parsable slice of SourceSystem.
type SourceSystems []*SourceSystem
