// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/space"
)

// Space is the model entity for the Space schema.
type Space struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// SpaceKey holds the value of the "SpaceKey" field.
	SpaceKey          string `json:"SpaceKey,omitempty"`
	collection_spaces *int
	confluence_spaces *int
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Space) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case space.FieldID:
			values[i] = new(sql.NullInt64)
		case space.FieldName, space.FieldSpaceKey:
			values[i] = new(sql.NullString)
		case space.ForeignKeys[0]: // collection_spaces
			values[i] = new(sql.NullInt64)
		case space.ForeignKeys[1]: // confluence_spaces
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Space fields.
func (s *Space) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case space.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case space.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case space.FieldSpaceKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field SpaceKey", values[i])
			} else if value.Valid {
				s.SpaceKey = value.String
			}
		case space.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field collection_spaces", value)
			} else if value.Valid {
				s.collection_spaces = new(int)
				*s.collection_spaces = int(value.Int64)
			}
		case space.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field confluence_spaces", value)
			} else if value.Valid {
				s.confluence_spaces = new(int)
				*s.confluence_spaces = int(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Space.
// This includes values selected through modifiers, order, etc.
func (s *Space) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Space.
// Note that you need to call Space.Unwrap() before calling this method if this Space
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Space) Update() *SpaceUpdateOne {
	return NewSpaceClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Space entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Space) Unwrap() *Space {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Space is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Space) String() string {
	var builder strings.Builder
	builder.WriteString("Space(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("Name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("SpaceKey=")
	builder.WriteString(s.SpaceKey)
	builder.WriteByte(')')
	return builder.String()
}

// Spaces is a parsable slice of Space.
type Spaces []*Space
