// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/space"
)

// SpaceCreate is the builder for creating a Space entity.
type SpaceCreate struct {
	config
	mutation *SpaceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "Name" field.
func (sc *SpaceCreate) SetName(s string) *SpaceCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetSpaceKey sets the "SpaceKey" field.
func (sc *SpaceCreate) SetSpaceKey(s string) *SpaceCreate {
	sc.mutation.SetSpaceKey(s)
	return sc
}

// Mutation returns the SpaceMutation object of the builder.
func (sc *SpaceCreate) Mutation() *SpaceMutation {
	return sc.mutation
}

// Save creates the Space in the database.
func (sc *SpaceCreate) Save(ctx context.Context) (*Space, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SpaceCreate) SaveX(ctx context.Context) *Space {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SpaceCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SpaceCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SpaceCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "Space.Name"`)}
	}
	if _, ok := sc.mutation.SpaceKey(); !ok {
		return &ValidationError{Name: "SpaceKey", err: errors.New(`ent: missing required field "Space.SpaceKey"`)}
	}
	return nil
}

func (sc *SpaceCreate) sqlSave(ctx context.Context) (*Space, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SpaceCreate) createSpec() (*Space, *sqlgraph.CreateSpec) {
	var (
		_node = &Space{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(space.Table, sqlgraph.NewFieldSpec(space.FieldID, field.TypeInt))
	)
	_spec.OnConflict = sc.conflict
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(space.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.SpaceKey(); ok {
		_spec.SetField(space.FieldSpaceKey, field.TypeString, value)
		_node.SpaceKey = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Space.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SpaceUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (sc *SpaceCreate) OnConflict(opts ...sql.ConflictOption) *SpaceUpsertOne {
	sc.conflict = opts
	return &SpaceUpsertOne{
		create: sc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Space.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sc *SpaceCreate) OnConflictColumns(columns ...string) *SpaceUpsertOne {
	sc.conflict = append(sc.conflict, sql.ConflictColumns(columns...))
	return &SpaceUpsertOne{
		create: sc,
	}
}

type (
	// SpaceUpsertOne is the builder for "upsert"-ing
	//  one Space node.
	SpaceUpsertOne struct {
		create *SpaceCreate
	}

	// SpaceUpsert is the "OnConflict" setter.
	SpaceUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "Name" field.
func (u *SpaceUpsert) SetName(v string) *SpaceUpsert {
	u.Set(space.FieldName, v)
	return u
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *SpaceUpsert) UpdateName() *SpaceUpsert {
	u.SetExcluded(space.FieldName)
	return u
}

// SetSpaceKey sets the "SpaceKey" field.
func (u *SpaceUpsert) SetSpaceKey(v string) *SpaceUpsert {
	u.Set(space.FieldSpaceKey, v)
	return u
}

// UpdateSpaceKey sets the "SpaceKey" field to the value that was provided on create.
func (u *SpaceUpsert) UpdateSpaceKey() *SpaceUpsert {
	u.SetExcluded(space.FieldSpaceKey)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Space.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SpaceUpsertOne) UpdateNewValues() *SpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Space.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SpaceUpsertOne) Ignore() *SpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SpaceUpsertOne) DoNothing() *SpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SpaceCreate.OnConflict
// documentation for more info.
func (u *SpaceUpsertOne) Update(set func(*SpaceUpsert)) *SpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SpaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "Name" field.
func (u *SpaceUpsertOne) SetName(v string) *SpaceUpsertOne {
	return u.Update(func(s *SpaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *SpaceUpsertOne) UpdateName() *SpaceUpsertOne {
	return u.Update(func(s *SpaceUpsert) {
		s.UpdateName()
	})
}

// SetSpaceKey sets the "SpaceKey" field.
func (u *SpaceUpsertOne) SetSpaceKey(v string) *SpaceUpsertOne {
	return u.Update(func(s *SpaceUpsert) {
		s.SetSpaceKey(v)
	})
}

// UpdateSpaceKey sets the "SpaceKey" field to the value that was provided on create.
func (u *SpaceUpsertOne) UpdateSpaceKey() *SpaceUpsertOne {
	return u.Update(func(s *SpaceUpsert) {
		s.UpdateSpaceKey()
	})
}

// Exec executes the query.
func (u *SpaceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SpaceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SpaceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SpaceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SpaceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SpaceCreateBulk is the builder for creating many Space entities in bulk.
type SpaceCreateBulk struct {
	config
	err      error
	builders []*SpaceCreate
	conflict []sql.ConflictOption
}

// Save creates the Space entities in the database.
func (scb *SpaceCreateBulk) Save(ctx context.Context) ([]*Space, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Space, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = scb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SpaceCreateBulk) SaveX(ctx context.Context) []*Space {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SpaceCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SpaceCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Space.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SpaceUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (scb *SpaceCreateBulk) OnConflict(opts ...sql.ConflictOption) *SpaceUpsertBulk {
	scb.conflict = opts
	return &SpaceUpsertBulk{
		create: scb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Space.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (scb *SpaceCreateBulk) OnConflictColumns(columns ...string) *SpaceUpsertBulk {
	scb.conflict = append(scb.conflict, sql.ConflictColumns(columns...))
	return &SpaceUpsertBulk{
		create: scb,
	}
}

// SpaceUpsertBulk is the builder for "upsert"-ing
// a bulk of Space nodes.
type SpaceUpsertBulk struct {
	create *SpaceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Space.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SpaceUpsertBulk) UpdateNewValues() *SpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Space.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SpaceUpsertBulk) Ignore() *SpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SpaceUpsertBulk) DoNothing() *SpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SpaceCreateBulk.OnConflict
// documentation for more info.
func (u *SpaceUpsertBulk) Update(set func(*SpaceUpsert)) *SpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SpaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "Name" field.
func (u *SpaceUpsertBulk) SetName(v string) *SpaceUpsertBulk {
	return u.Update(func(s *SpaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "Name" field to the value that was provided on create.
func (u *SpaceUpsertBulk) UpdateName() *SpaceUpsertBulk {
	return u.Update(func(s *SpaceUpsert) {
		s.UpdateName()
	})
}

// SetSpaceKey sets the "SpaceKey" field.
func (u *SpaceUpsertBulk) SetSpaceKey(v string) *SpaceUpsertBulk {
	return u.Update(func(s *SpaceUpsert) {
		s.SetSpaceKey(v)
	})
}

// UpdateSpaceKey sets the "SpaceKey" field to the value that was provided on create.
func (u *SpaceUpsertBulk) UpdateSpaceKey() *SpaceUpsertBulk {
	return u.Update(func(s *SpaceUpsert) {
		s.UpdateSpaceKey()
	})
}

// Exec executes the query.
func (u *SpaceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SpaceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SpaceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SpaceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
