// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/space"
)

// SpaceUpdate is the builder for updating Space entities.
type SpaceUpdate struct {
	config
	hooks    []Hook
	mutation *SpaceMutation
}

// Where appends a list predicates to the SpaceUpdate builder.
func (su *SpaceUpdate) Where(ps ...predicate.Space) *SpaceUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "Name" field.
func (su *SpaceUpdate) SetName(s string) *SpaceUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableName(s *string) *SpaceUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetSpaceKey sets the "SpaceKey" field.
func (su *SpaceUpdate) SetSpaceKey(s string) *SpaceUpdate {
	su.mutation.SetSpaceKey(s)
	return su
}

// SetNillableSpaceKey sets the "SpaceKey" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableSpaceKey(s *string) *SpaceUpdate {
	if s != nil {
		su.SetSpaceKey(*s)
	}
	return su
}

// Mutation returns the SpaceMutation object of the builder.
func (su *SpaceUpdate) Mutation() *SpaceMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SpaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SpaceUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SpaceUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SpaceUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SpaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(space.Table, space.Columns, sqlgraph.NewFieldSpec(space.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(space.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.SpaceKey(); ok {
		_spec.SetField(space.FieldSpaceKey, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{space.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SpaceUpdateOne is the builder for updating a single Space entity.
type SpaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpaceMutation
}

// SetName sets the "Name" field.
func (suo *SpaceUpdateOne) SetName(s string) *SpaceUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableName(s *string) *SpaceUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetSpaceKey sets the "SpaceKey" field.
func (suo *SpaceUpdateOne) SetSpaceKey(s string) *SpaceUpdateOne {
	suo.mutation.SetSpaceKey(s)
	return suo
}

// SetNillableSpaceKey sets the "SpaceKey" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableSpaceKey(s *string) *SpaceUpdateOne {
	if s != nil {
		suo.SetSpaceKey(*s)
	}
	return suo
}

// Mutation returns the SpaceMutation object of the builder.
func (suo *SpaceUpdateOne) Mutation() *SpaceMutation {
	return suo.mutation
}

// Where appends a list predicates to the SpaceUpdate builder.
func (suo *SpaceUpdateOne) Where(ps ...predicate.Space) *SpaceUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SpaceUpdateOne) Select(field string, fields ...string) *SpaceUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Space entity.
func (suo *SpaceUpdateOne) Save(ctx context.Context) (*Space, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SpaceUpdateOne) SaveX(ctx context.Context) *Space {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SpaceUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SpaceUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SpaceUpdateOne) sqlSave(ctx context.Context) (_node *Space, err error) {
	_spec := sqlgraph.NewUpdateSpec(space.Table, space.Columns, sqlgraph.NewFieldSpec(space.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Space.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, space.FieldID)
		for _, f := range fields {
			if !space.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != space.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(space.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.SpaceKey(); ok {
		_spec.SetField(space.FieldSpaceKey, field.TypeString, value)
	}
	_node = &Space{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{space.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
