// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/collection"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/confluence"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/predicate"
	"github.com/vogtp/rag/pkg/usercfg/db/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetName sets the "Name" field.
func (uu *UserUpdate) SetName(s string) *UserUpdate {
	uu.mutation.SetName(s)
	return uu
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (uu *UserUpdate) SetNillableName(s *string) *UserUpdate {
	if s != nil {
		uu.SetName(*s)
	}
	return uu
}

// SetOpenaiAPIkey sets the "OpenaiAPIkey" field.
func (uu *UserUpdate) SetOpenaiAPIkey(s string) *UserUpdate {
	uu.mutation.SetOpenaiAPIkey(s)
	return uu
}

// SetNillableOpenaiAPIkey sets the "OpenaiAPIkey" field if the given value is not nil.
func (uu *UserUpdate) SetNillableOpenaiAPIkey(s *string) *UserUpdate {
	if s != nil {
		uu.SetOpenaiAPIkey(*s)
	}
	return uu
}

// ClearOpenaiAPIkey clears the value of the "OpenaiAPIkey" field.
func (uu *UserUpdate) ClearOpenaiAPIkey() *UserUpdate {
	uu.mutation.ClearOpenaiAPIkey()
	return uu
}

// AddConfluenceIDs adds the "Confluence" edge to the Confluence entity by IDs.
func (uu *UserUpdate) AddConfluenceIDs(ids ...int) *UserUpdate {
	uu.mutation.AddConfluenceIDs(ids...)
	return uu
}

// AddConfluence adds the "Confluence" edges to the Confluence entity.
func (uu *UserUpdate) AddConfluence(c ...*Confluence) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.AddConfluenceIDs(ids...)
}

// AddCollectionIDs adds the "Collections" edge to the Collection entity by IDs.
func (uu *UserUpdate) AddCollectionIDs(ids ...int) *UserUpdate {
	uu.mutation.AddCollectionIDs(ids...)
	return uu
}

// AddCollections adds the "Collections" edges to the Collection entity.
func (uu *UserUpdate) AddCollections(c ...*Collection) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.AddCollectionIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearConfluence clears all "Confluence" edges to the Confluence entity.
func (uu *UserUpdate) ClearConfluence() *UserUpdate {
	uu.mutation.ClearConfluence()
	return uu
}

// RemoveConfluenceIDs removes the "Confluence" edge to Confluence entities by IDs.
func (uu *UserUpdate) RemoveConfluenceIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveConfluenceIDs(ids...)
	return uu
}

// RemoveConfluence removes "Confluence" edges to Confluence entities.
func (uu *UserUpdate) RemoveConfluence(c ...*Confluence) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.RemoveConfluenceIDs(ids...)
}

// ClearCollections clears all "Collections" edges to the Collection entity.
func (uu *UserUpdate) ClearCollections() *UserUpdate {
	uu.mutation.ClearCollections()
	return uu
}

// RemoveCollectionIDs removes the "Collections" edge to Collection entities by IDs.
func (uu *UserUpdate) RemoveCollectionIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveCollectionIDs(ids...)
	return uu
}

// RemoveCollections removes "Collections" edges to Collection entities.
func (uu *UserUpdate) RemoveCollections(c ...*Collection) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.RemoveCollectionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := uu.mutation.OpenaiAPIkey(); ok {
		_spec.SetField(user.FieldOpenaiAPIkey, field.TypeString, value)
	}
	if uu.mutation.OpenaiAPIkeyCleared() {
		_spec.ClearField(user.FieldOpenaiAPIkey, field.TypeString)
	}
	if uu.mutation.ConfluenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConfluenceTable,
			Columns: []string{user.ConfluenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedConfluenceIDs(); len(nodes) > 0 && !uu.mutation.ConfluenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConfluenceTable,
			Columns: []string{user.ConfluenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.ConfluenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConfluenceTable,
			Columns: []string{user.ConfluenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CollectionsTable,
			Columns: []string{user.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedCollectionsIDs(); len(nodes) > 0 && !uu.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CollectionsTable,
			Columns: []string{user.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CollectionsTable,
			Columns: []string{user.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "Name" field.
func (uuo *UserUpdateOne) SetName(s string) *UserUpdateOne {
	uuo.mutation.SetName(s)
	return uuo
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableName(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetName(*s)
	}
	return uuo
}

// SetOpenaiAPIkey sets the "OpenaiAPIkey" field.
func (uuo *UserUpdateOne) SetOpenaiAPIkey(s string) *UserUpdateOne {
	uuo.mutation.SetOpenaiAPIkey(s)
	return uuo
}

// SetNillableOpenaiAPIkey sets the "OpenaiAPIkey" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableOpenaiAPIkey(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetOpenaiAPIkey(*s)
	}
	return uuo
}

// ClearOpenaiAPIkey clears the value of the "OpenaiAPIkey" field.
func (uuo *UserUpdateOne) ClearOpenaiAPIkey() *UserUpdateOne {
	uuo.mutation.ClearOpenaiAPIkey()
	return uuo
}

// AddConfluenceIDs adds the "Confluence" edge to the Confluence entity by IDs.
func (uuo *UserUpdateOne) AddConfluenceIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddConfluenceIDs(ids...)
	return uuo
}

// AddConfluence adds the "Confluence" edges to the Confluence entity.
func (uuo *UserUpdateOne) AddConfluence(c ...*Confluence) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.AddConfluenceIDs(ids...)
}

// AddCollectionIDs adds the "Collections" edge to the Collection entity by IDs.
func (uuo *UserUpdateOne) AddCollectionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddCollectionIDs(ids...)
	return uuo
}

// AddCollections adds the "Collections" edges to the Collection entity.
func (uuo *UserUpdateOne) AddCollections(c ...*Collection) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.AddCollectionIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearConfluence clears all "Confluence" edges to the Confluence entity.
func (uuo *UserUpdateOne) ClearConfluence() *UserUpdateOne {
	uuo.mutation.ClearConfluence()
	return uuo
}

// RemoveConfluenceIDs removes the "Confluence" edge to Confluence entities by IDs.
func (uuo *UserUpdateOne) RemoveConfluenceIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveConfluenceIDs(ids...)
	return uuo
}

// RemoveConfluence removes "Confluence" edges to Confluence entities.
func (uuo *UserUpdateOne) RemoveConfluence(c ...*Confluence) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.RemoveConfluenceIDs(ids...)
}

// ClearCollections clears all "Collections" edges to the Collection entity.
func (uuo *UserUpdateOne) ClearCollections() *UserUpdateOne {
	uuo.mutation.ClearCollections()
	return uuo
}

// RemoveCollectionIDs removes the "Collections" edge to Collection entities by IDs.
func (uuo *UserUpdateOne) RemoveCollectionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveCollectionIDs(ids...)
	return uuo
}

// RemoveCollections removes "Collections" edges to Collection entities.
func (uuo *UserUpdateOne) RemoveCollections(c ...*Collection) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.RemoveCollectionIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := uuo.mutation.OpenaiAPIkey(); ok {
		_spec.SetField(user.FieldOpenaiAPIkey, field.TypeString, value)
	}
	if uuo.mutation.OpenaiAPIkeyCleared() {
		_spec.ClearField(user.FieldOpenaiAPIkey, field.TypeString)
	}
	if uuo.mutation.ConfluenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConfluenceTable,
			Columns: []string{user.ConfluenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedConfluenceIDs(); len(nodes) > 0 && !uuo.mutation.ConfluenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConfluenceTable,
			Columns: []string{user.ConfluenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.ConfluenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConfluenceTable,
			Columns: []string{user.ConfluenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(confluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CollectionsTable,
			Columns: []string{user.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedCollectionsIDs(); len(nodes) > 0 && !uuo.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CollectionsTable,
			Columns: []string{user.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CollectionsTable,
			Columns: []string{user.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
