// Code generated by "stringer -type=BackendApiType --trimprefix BackendApiType"; DO NOT EDIT.

package cfg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BackendApiTypeOllama-0]
	_ = x[BackendApiTypeOpenai-1]
	_ = x[BackendApiTypeUnknown-2]
}

const _BackendApiType_name = "OllamaOpenaiUnknown"

var _BackendApiType_index = [...]uint8{0, 6, 12, 19}

func (i BackendApiType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BackendApiType_index)-1 {
		return "BackendApiType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BackendApiType_name[_BackendApiType_index[idx]:_BackendApiType_index[idx+1]]
}
