// Code generated by "stringer -type=SourceSystemType --trimprefix Source"; DO NOT EDIT.

package usercfg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceConfluence-0]
	_ = x[SourceHTTP-1]
}

const _SourceSystemType_name = "ConfluenceHTTP"

var _SourceSystemType_index = [...]uint8{0, 10, 14}

func (i SourceSystemType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SourceSystemType_index)-1 {
		return "SourceSystemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceSystemType_name[_SourceSystemType_index[idx]:_SourceSystemType_index[idx+1]]
}
