// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// SourceSystem is the predicate function for sourcesystem builders.
type SourceSystem func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
